import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import "@/app/globals.css"


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} >
        {/* <main className=' bg-primary '> */}
        <Navbar />
        {children}
        {/* </main> */}
      </body>
    </html>
  )
}
